# api port
port: "1234"

# push service configuration
push:
  default_provider: "expo"
  default_sound: "default"
  default_ttl: 3600
  default_priority: "normal"
  max_retries: 3
  retry_interval: "1s"
  batch_size: 100
  batch_timeout: "30s"
  max_concurrency: 6
  enable_stats: true
  stats_interval: "5m"
  health_check_interval: "10m"
  providers:
    expo:
      access_token: ""
      timeout: "30s"
      max_retries: 3
      base_delay: "1s"
      default_sound: "default"
      default_ttl: 3600
      default_priority: "normal"
      batch_size: 100
      max_concurrency: 6

# push center configuration
push_center:
  enabled: true
  db_path: "./data/push_center_pebble"

# socket.io client configuration
socket_client:
  server_url: "https://your-server-url"
  extra_push_auth_key: "your-extra-push-auth-key"
  path: "/socket/socket.io/"
  timeout: 10  # seconds
